from lib import *

# ---------------------------------------------------------------- 155 --
# a genuine translational tiling of a 6 x 12 window by an S-tetromino,
# lattice generated by (0,2) and (2,1) in (row, col)
T = [(0, 0), (0, 1), (1, 1), (1, 2)]
G1, G2 = (0, 2), (2, 1)
owner = {}
for i in range(-12, 13):
    for j in range(-12, 13):
        for (dr, dc) in T:
            q = (dr + i * G1[0] + j * G2[0], dc + i * G1[1] + j * G2[1])
            assert q not in owner
            owner[q] = (i, j)
ROWS, COLS = 6, 12
cells = []
tones = ['accent', 'cool', 'warn']
for r in range(ROWS):
    for c in range(COLS):
        i, j = owner[(r, c)]
        cells.append([r, c, tones[(i + 2 * j) % 3]])
# neighbouring tiles must differ in colour
for r in range(ROWS):
    for c in range(COLS):
        for (r2, c2) in [(r + 1, c), (r, c + 1)]:
            if r2 < ROWS and c2 < COLS and owner[(r, c)] != owner[(r2, c2)]:
                assert cells[r * COLS + c][2] != cells[r2 * COLS + c2][2], (r, c)

write({
    'id': '155', 'discipline': 'Combinatorics', 'kind': 'counterexample',
    'short': 'Periodic tiling fails in $\\mathbb Z^3$',
    'title': {'title': 'A tile in $\\mathbb Z^3$ with no periodic tiling',
              'subtitle': 'Claim: a finite tile tiles $\\mathbb Z^3$ by translations but never periodically, so the conjecture fails at $d = 3$'},
    'object': {
        'dur': 8.4, 'layout': 'sequence',
        'panels': [
            {'primitive': 'grid', 'rows': ROWS, 'cols': COLS, 'cells': cells, 'stagger': 0.03,
             'caption': 'one tile, its translates repeating with a period (an illustration in $\\mathbb Z^2$)', 'until': 3.9},
            {'primitive': 'numberline', 'from': 3.9, 'min': 0.5, 'max': 5.5, 'ticks': [1, 2, 3],
             'axisLabel': 'the dimension $d$ of $\\mathbb Z^d$',
             'markers': [
                 {'v': 1, 'label': 'periodic', 'note': 'Newman 1977', 'tone': 'ok', 'at': 0.5},
                 {'v': 2, 'label': 'periodic', 'note': 'Bhattacharya 2020', 'tone': 'ok', 'at': 0.8},
                 {'v': 5, 'label': 'fails, huge $d$', 'note': 'Greenfeld–Tao 2022', 'style': 'ring', 'tone': 'mute', 'at': 1.1}],
             'slide': {'from': 5, 'to': 3, 'at': 2.0, 'dur': 1.5, 'label': 'fails at $d = 3$', 'note': 'claimed, least possible'}}],
        'beats': [
            {'at': 0.2, 'text': 'A tile that tiles $\\mathbb Z^2$ by translations can always tile it periodically'},
            {'at': 4.0, 'text': 'Greenfeld and Tao broke the conjecture in 2022, in a huge unspecified dimension'},
            {'at': 6.3, 'text': 'The claim: it already fails in $\\mathbb Z^3$ and $\\mathbb R^3$, the least dimension possible'}]},
    'achievement': {
        'form': 'status', 'label': 'Periodic tiling conjecture (Lagarias–Wang, 1996)',
        'statement': ['T \\oplus A = \\mathbb Z^d \\;\\Rightarrow\\; \\text{some such } A \\text{ is fully periodic}'],
        'context': 'Claimed counterexample: a tile in $\\mathbb Z^3$, and its cube thickening in $\\mathbb R^3$',
        'stamp': 'counterexample',
        'note': 'No size is given for the tile; it is presumably astronomically large'},
    'verify': {'lean': 'main',
               'detail': 'Both the $\\mathbb Z^3$ and $\\mathbb R^3$ claims plus minimality, so it re-proves $d = 1, 2$',
               'ourCheck': LEAN_MAIN_CHECK},
    'sources': [
        R('155', 'known_before', 'Lagarias & Wang, Invent. Math. 1996'),
        R('155', 'known_before', 'Known true in d=1 (Newman 1977)'),
        R('155', 'known_before', 'Bhattacharya, arXiv 1602.05738, Discrete Analysis 2020'),
        A('Periodic tiling fails in dimension 3', 'Greenfeld and Tao disproved it in 2022 in some huge, unspecified dimension'),
        R('155', 'claim', 'd=3 is the least lattice dimension where the periodic tiling conjecture fails'),
        R('155', 'caveats', 'The tile is presumably astronomically large'),
        R('155', 'caveats', 'no explicit size given'),
        R('155', 'lean', 'covers both the Z^3 and the R^3 (a.e. tiling, arbitrary real lattice) assertions AND the minimality IsLeast {d | ...} 3, so the Lean also re-proves the d=1 and d=2 positive results'),
        R('155', 'lean', 'Comparator not re-run by me'),
    ]})

# ---------------------------------------------------------------- 156 --
write({
    'id': '156', 'discipline': 'Combinatorics', 'kind': 'counterexample',
    'short': "Borsuk's conjecture fails in $d = 9$",
    'title': {'title': "Borsuk's conjecture fails in dimension nine",
              'subtitle': 'Claim: the rank-one projectors $uu^\\top$, $u \\in \\mathbb R^4$, cannot be cut into 10 pieces of smaller diameter'},
    'object': {
        'dur': 8.4, 'primitive': 'numberline', 'min': 0, 'max': 1400, 'ticks': [],
        'axisLabel': 'the dimension $d$ where Borsuk fails',
        'markers': [
            {'v': 1325, 'label': 'Kahn–Kalai', 'note': '1993', 'at': 0.6},
            {'v': 64, 'label': 'Jenrich–Brouwer', 'note': '2014', 'at': 3.6},
            {'v': 63, 'label': 'Grinsztajn', 'note': 'May 2026', 'at': 3.9}],
        'zoom': {'min': 0, 'max': 72, 'at': 1.4, 'dur': 2.0, 'counter': False,
                 'ticks': [{'v': 9, 'label': '9'}, {'v': 63, 'label': '63'}]},
        'slide': {'from': 63, 'to': 9, 'at': 4.6, 'dur': 1.5, 'label': 'claimed $d = 9$', 'note': 'projectors $uu^\\top$'},
        'beats': [
            {'at': 0.2, 'text': 'Borsuk, 1933: can every bounded set in $\\mathbb R^d$ be cut into $d+1$ smaller pieces?'},
            {'at': 3.0, 'text': 'Kahn and Kalai said no in dimension 1325. By May 2026 the record was 63'},
            {'at': 5.9, 'text': 'The claim: lines through the origin of $\\mathbb R^4$ need more than 10 pieces'}]},
    'achievement': {
        'form': 'bound', 'stamp': 'counterexample',
        'before': {'label': 'Lowest known, 2026', 'tex': 'd = 63', 'note': 'Grinsztajn with GPT-5.5 Pro'},
        'after': {'label': 'Claimed, Sep 2026', 'tex': 'd = 9', 'note': 'and every $d \\ge 9$'},
        'note': 'The least failing dimension is now somewhere between 4 and 9'},
    'verify': {'lean': 'main',
               'detail': 'Compact, diameter $\\sqrt 2$, no cover by ten smaller sets; 145 generated case files',
               'ourCheck': LEAN_MAIN_CHECK},
    'sources': [
        R('156', 'known_before', 'Posed by Borsuk 1933'),
        R('156', 'known_before', 'Disproved by Kahn–Kalai 1993 (d=1325; arXiv math/9307229)'),
        R('156', 'known_before', 'Jenrich–Brouwer 64 (Electron. J. Combin. 2014)'),
        R('156', 'known_before', 'Then Max Grinsztajn, assisted by GPT-5.5 Pro, dimension 63 (321-point three-distance set; arXiv 2608.12561, Wikipedia dates it May 2026)'),
        A('Borsuk', 'then 63 in 2026 (Grinsztajn with GPT-5.5 Pro, arXiv 2608.12561)'),
        C('156', 'cannot be covered by 10 sets of diameter < √2'),
        R('156', 'claim', 'in every d ≥ 9'),
        A('Borsuk', 'It does not find the smallest failing dimension, which is now somewhere between 4 and 9'),
        A('Borsuk', 'That analysis is in Lean as 145 generated case files'),
        C('156', 'September-23-2026'),
    ]})

# ---------------------------------------------------------------- 157 --
write({
    'id': '157', 'discipline': 'Combinatorics', 'kind': 'disproof',
    'short': "Hadwiger's conjecture, disproved on paper",
    'title': {'title': "Hadwiger's conjecture fails, even fractionally",
              'subtitle': 'Claim: large graphs with $\\alpha(G) \\le 2$ have $\\chi_f(G) > h(G)$; separately, $\\chi_{\\text{list}}(G) \\le C\\,h(G)$'},
    'object': {
        'dur': 8.4, 'layout': 'sequence',
        'panels': [
            {'primitive': 'graph', 'r': 22, 'until': 4.0, 'edgeAt': 0.5, 'edgeDur': 2.2,
             'nodes': [
                 {'id': 'a1', 'x': 0.32, 'y': 0.18, 'label': '$A_1$'}, {'id': 'a2', 'x': 0.32, 'y': 0.82, 'label': '$A_2$'},
                 {'id': 'b1', 'x': 0.68, 'y': 0.18, 'label': '$B_1$'}, {'id': 'b2', 'x': 0.68, 'y': 0.82, 'label': '$B_2$'}],
             'edges': [['a1', 'a2', {'tone': 'accent', 'w': 4}], ['b1', 'b2', {'tone': 'accent', 'w': 4}],
                       ['a1', 'b1', {'tone': 'bad', 'w': 1.6, 'a': 0.5}], ['a1', 'b2', {'tone': 'bad', 'w': 1.6, 'a': 0.5}],
                       ['a2', 'b1', {'tone': 'bad', 'w': 1.6, 'a': 0.5}], ['a2', 'b2', {'tone': 'bad', 'w': 1.6, 'a': 0.5}]]},
            {'primitive': 'numberline', 'from': 4.0, 'min': 0, 'max': 0.62, 'y': 0.6,
             'ticks': [0, {'v': 0.5, 'label': '$m/2$'}],
             'axisLabel': 'as a fraction of $m$, the number of vertices',
             'markers': [
                 {'v': 0.346667, 'derived': '26/75', 'label': 'clique minor $h$', 'note': '$< 26m/75 + 2/3$', 'at': 0.5},
                 {'v': 0.5, 'derived': '1/2', 'label': 'colours $\\chi_f$', 'note': 'at least $m/2$', 'tone': 'claim', 'at': 1.0}],
             'ranges': [{'from': 0.346667, 'to': 0.5, 'derived': '26/75 to 1/2', 'label': '$\\chi_f > h$', 'tone': 'hot', 'side': 'below', 'at': 1.8}]}],
        'beats': [
            {'at': 0.2, 'text': 'Two matching edges whose four cross pairs are holes cannot share a connected matching'},
            {'at': 4.1, 'text': 'With $\\alpha(G) \\le 2$ you need $m/2$ colours; the clique minor stays below $26m/75 + 2/3$'},
            {'at': 6.6, 'text': 'So $\\chi_f(G) > h(G)$, if the 235 pages of counterexample hold'}]},
    'achievement': {
        'form': 'status', 'label': "Hadwiger's conjecture (1943)",
        'statement': ['\\chi(G) \\le h(G)', '\\text{claimed: } \\chi_f(G) > h(G) \\text{ for arbitrarily large graphs}'],
        'context': "Also claimed: Colin de Verdière's $\\chi \\le \\mu + 1$ fails, and $\\chi_{\\text{list}} \\le C\\,h$ holds",
        'stamp': 'disproved',
        'note': 'The counterexamples are manuscript only, with no explicit graph'},
    'verify': {'lean': 'part',
               'detail': 'In Lean: only the linear bound $\\chi_{\\text{list}}(G) \\le C\\,h(G)$. Not the counterexamples',
               'ourCheck': LEAN_MAIN_CHECK},
    'sources': [
        R('157', 'known_before', 'Hadwiger 1943'),
        A('Hadwiger', 'a known inequality turns the small connected matching into a clique-minor bound $h(G) \\lt 26m/75 + 2/3$, which is below $m/2$'),
        A('Hadwiger', 'With $\\alpha(G) \\le 2$ you need at least $m/2$ colours even fractionally'),
        A('Hadwiger', '235 pages of new probabilistic and algebraic machinery that nobody outside OpenAI has checked'),
        R('157', 'lean', 'only paper 3 (linear list bound) is formalized'),
        R('157', 'lean', 'The Hadwiger counterexample (104 pp) and the Colin de Verdière counterexample (131 pp) have no Lean formalization.'),
        R('157', 'claim', 'Counterexamples are probabilistic/existential for large m; no explicit graph.'),
    ]})

# ---------------------------------------------------------------- 158 --
phi = 2 * math.asin(1 / (2 * math.sqrt(3)))
a1, a2 = math.pi / 2 - phi / 2, math.pi / 2 + phi / 2
pol = lambda r, t: (r * math.cos(t), r * math.sin(t))
P = {'o': (0, 0), 'p1': pol(1, a1 - math.pi / 6), 'q1': pol(1, a1 + math.pi / 6), 't1': pol(math.sqrt(3), a1),
     'p2': pol(1, a2 - math.pi / 6), 'q2': pol(1, a2 + math.pi / 6), 't2': pol(math.sqrt(3), a2)}
E = [('o', 'p1'), ('o', 'q1'), ('p1', 'q1'), ('p1', 't1'), ('q1', 't1'),
     ('o', 'p2'), ('o', 'q2'), ('p2', 'q2'), ('p2', 't2'), ('q2', 't2'), ('t1', 't2')]
for u, v in E:
    d = math.dist(P[u], P[v]); assert abs(d - 1) < 1e-9, (u, v, d)
import itertools
names = list(P)
col = None
for cs in itertools.product(range(4), repeat=7):
    m = dict(zip(names, cs))
    if all(m[u] != m[v] for u, v in E):
        col = m; break
ys = [p[1] for p in P.values()]
sc = 215
cy = 352 + (max(ys) + min(ys)) / 2 * sc
fr = dict(zip(names, place([P[k] for k in names], cy=cy, scale=sc)))
FILL = ['accent', 'cool', 'warn', 'bad']
write({
    'id': '158', 'discipline': 'Combinatorics', 'kind': 'improved-bound',
    'short': 'The plane is not five-colourable',
    'title': {'title': 'The plane cannot be coloured with five colours',
              'subtitle': 'Claim: every 5-colouring of $\\mathbb R^2$ has two points at distance 1 in one colour, so $6 \\le \\chi(\\mathbb R^2) \\le 7$'},
    'object': {
        'dur': 8.4, 'layout': 'sequence',
        'panels': [
            {'primitive': 'graph', 'r': 15, 'until': 3.7, 'edgeAt': 0.4, 'edgeDur': 2.0,
             'nodes': [{'id': k, 'x': fr[k][0], 'y': fr[k][1], 'fill': FILL[col[k]]} for k in names],
             'edges': [[u, v, {'tone': 'hot' if (u, v) == ('t1', 't2') else 'soft'}] for u, v in E]},
            {'primitive': 'numberline', 'from': 3.7, 'min': 3.4, 'max': 7.6, 'ticks': [4, 5, 6, 7],
             'axisLabel': 'colours needed for the plane, $\\chi(\\mathbb R^2)$',
             'markers': [
                 {'v': 4, 'label': 'Moser spindle', 'note': '1961', 'at': 0.5},
                 {'v': 5, 'label': 'de Grey', 'note': '2018, 1581 vertices', 'at': 0.8},
                 {'v': 7, 'label': 'upper bound', 'note': 'Isbell, 7 colours', 'style': 'ring', 'tone': 'mute', 'at': 1.1}],
             'slide': {'from': 5, 'to': 6, 'at': 1.6, 'dur': 1.4, 'label': 'claimed $\\ge 6$', 'note': 'any colouring'}}],
        'beats': [
            {'at': 0.2, 'text': 'The Moser spindle: seven points, every edge of length 1, and four colours needed'},
            {'at': 3.8, 'text': 'Since 2018 the answer was known to be 5, 6 or 7'},
            {'at': 6.4, 'text': 'The claim: five colours never suffice, measurable or not'}]},
    'achievement': {
        'form': 'bound',
        'before': {'label': 'Best known, since 2018', 'tex': '\\chi(\\mathbb R^2) \\ge 5', 'note': "de Grey's 1581-vertex graph"},
        'after': {'label': 'Claimed, Sep 2026', 'tex': '6 \\le \\chi(\\mathbb R^2) \\le 7', 'note': 'arbitrary colourings, no regularity assumed'},
        'note': 'Non-constructive: no finite 6-chromatic unit-distance graph is exhibited'},
    'verify': {'lean': 'main',
               'detail': 'No map $\\mathbb C \\to \\mathrm{Fin}\\,5$ separates every unit pair; no measurability assumed',
               'ourCheck': LEAN_MAIN_CHECK},
    'sources': [
        R('158', 'known_before', 'Lower bound 4 (Moser spindle 1961)'),
        A('The plane is not five-colourable', "Aubrey de Grey's 1581-vertex graph pushed the lower bound to 5 in 2018"),
        R('158', 'explainer', 'since 2018 the answer was known to be 5, 6 or 7'),
        R('158', 'known_before', 'Nelson 1950 / Isbell (7-colouring)'),
        R('158', 'claim', 'Hence 6 ≤ χ(R^2) ≤ 7'),
        R('158', 'claim', 'Non-constructive: implies, by de Bruijn–Erdős, a finite 6-chromatic unit-distance graph exists, but none is exhibited.'),
        C('158', 'The-Euclidean-plane-is-not-five-colorable-September-23-2026'),
        A('The plane is not five-colourable', 'no function `ℂ → Fin 5` separates every pair at distance 1 (`EuclideanFiveColor.lean:10`), with no measurability assumption anywhere'),
    ]})

# ---------------------------------------------------------------- 159 --
write({
    'id': '159', 'discipline': 'Combinatorics', 'kind': 'proof',
    'short': '$\\textsf{Erd\\H{o}s}$ reciprocal-sum conjecture',
    'title': {'title': 'Divergent reciprocal sums force long progressions',
              'subtitle': 'Claim: if $\\sum_{a \\in A} 1/a = \\infty$, then $A$ has arithmetic progressions of every finite length'},
    'object': {
        'dur': 8.4, 'primitive': 'plot', 'x': [2, 30], 'y': [0, 0.5], 'labelRoom': 250,
        'xlabel': '$\\log N$', 'ylabel': '$r_k(N)/N$, schematic',
        'curves': [
            {'f': 'pow(x,-1.1)', 'label': '$(\\log N)^{-1-\\epsilon}$: the target', 'tone': 'mute', 'dash': True, 'at': 0.6, 'labelDy': -12},
            {'f': 'exp(-sqrt(log(x)))', 'label': '$e^{-(\\log\\log N)^{c}}$, 2024', 'tone': 'soft', 'at': 2.6},
            {'f': 'exp(-0.9*pow(x,0.5))', 'label': 'claimed $e^{-c_k(\\log N)^{\\varepsilon_k}}$', 'tone': 'accent', 'at': 5.0, 'labelDy': 12}],
        'beats': [
            {'at': 0.2, 'text': 'Erdős asked: does $\\sum 1/a = \\infty$, as for the primes, force progressions of every length?'.replace('Erdős', '$\\textsf{Erd\\H{o}s}$')},
            {'at': 2.8, 'text': 'That needs $r_k(N)/N$ below $(\\log N)^{-1-\\epsilon}$; for $k \\ge 5$ the best bound was not'},
            {'at': 5.3, 'text': 'Schematic curves. The claim: $C_k\\,e^{-c_k(\\log N)^{\\varepsilon_k}}$ for every $k \\ge 3$'}]},
    'achievement': {
        'form': 'status', 'label': 'Reciprocal-sum conjecture (1974), erdosproblems #3',
        'statement': ['\\textstyle\\sum_{a \\in A} \\frac1a = \\infty \\;\\Rightarrow\\; A \\text{ has } k\\text{-term APs for every } k'],
        'context': 'Before: only $k = 3$ had a strong enough bound (Kelley–Meka, 2023)',
        'stamp': 'proved',
        'note': 'Lean reaches the corollary by a weaker bound; Theorem 1.1 is unchecked'},
    'verify': {'lean': 'part',
               'detail': 'In Lean: the $\\textsf{Erd\\H{o}s}$ statement, via $N e^{-c(\\log\\log N)^{1+\\eta}}$. Not Theorem 1.1',
               'ourCheck': LEAN_MAIN_CHECK},
    'sources': [
        R('159', 'known_before', 'Erdős 1974, Math. Balkanica'),
        R('159', 'known_before', 'Kelley–Meka 2023'),
        A("Erdős's \\$5000 progression problem", 'What the conjecture needs is a Szemerédi bound $r_k(N)$ that decays faster than $N/(\\log N)^{1+\\epsilon}$'),
        A("Erdős's \\$5000 progression problem", "For $k \\ge 5$ the best was Leng, Sah and Sawhney's $N \\exp(-(\\log \\log N)^{c})$ from 2024, which is not summable over dyadic scales"),
        R('159', 'lean', 'The quantitative Theorem 1.1 is NOT a comparator target'),
        R('159', 'lean', 'Lean not built by this reviewer'),
    ]})

# ---------------------------------------------------------------- 160 --
write({
    'id': '160', 'discipline': 'Combinatorics', 'kind': 'proof',
    'short': 'Van der Waerden numbers, superexponential',
    'title': {'title': 'Van der Waerden numbers grow superexponentially',
              'subtitle': 'Claim: $W_r(k) > k^{c\\,k \\lfloor \\log_2 r \\rfloor}$ for all large $k$ and every $r \\ge 2$, two colours included'},
    'object': {
        'dur': 8.4, 'layout': 'sequence',
        'panels': [
            {'primitive': 'sequence', 'items': ['1', '2', '3', '4', '5', '6', '7', '8'], 'until': 3.9, 'stagger': 0.12,
             'marks': {'0': 'accent', '1': 'accent', '4': 'accent', '5': 'accent', '2': 'cool', '3': 'cool', '6': 'cool', '7': 'cool'},
             'caption': 'two colours on $1, \\dots, 8$ with no one-colour 3-term progression'},
            {'primitive': 'equation', 'from': 3.9,
             'lines': [
                 {'tex': 'W_2(k) \\ge (1-o(1))\\,k\\,2^{k-1}', 'note': 'Aug 2026', 'tone': 'mute', 'at': 0.4},
                 {'tex': 'W_r(k) > k^{c\\,k \\lfloor \\log_2 r \\rfloor}', 'note': 'claimed', 'tone': 'claim', 'at': 1.6},
                 {'tex': 'W_r(k)^{1/k} \\to \\infty', 'note': 'for each fixed $r$', 'at': 2.6}]}],
        'beats': [
            {'at': 0.2, 'text': '$W_r(k)$: the shortest interval where every $r$-colouring has a one-colour $k$-term progression'},
            {'at': 4.0, 'text': 'For two colours the best constructions gave only about $k\\,2^k$'},
            {'at': 6.5, 'text': 'The claim: $k^{c k}$ growth, settling $\\textsf{Erd\\H{o}s}$\'s question, with $c = 10^{-5}$'}]},
    'achievement': {
        'form': 'status', 'label': 'Superexponential growth of van der Waerden numbers (1980)',
        'statement': ['W_r(k) > k^{c\\,k \\lfloor \\log_2 r \\rfloor},\\quad c = 10^{-5}'],
        'context': 'Before: three colours only (Fox–Hunter, June 2026); for two, $W_2(k)/2^k \\to \\infty$ (Aug 2026)',
        'stamp': 'proved',
        'note': 'The threshold $K_0$ is ineffective'},
    'verify': {'lean': 'main',
               'detail': 'The exact headline bound $k^{10^{-5} k \\log_2 r} < W(r,k)$ is in Lean, and listed',
               'ourCheck': LEAN_MAIN_CHECK},
    'sources': [
        R('160', 'claim', 'There are absolute K_0 and c = 10^{-5} such that W_r(k) > k^{c k floor(log2 r)} for every k >= K_0 and every r >= 2'),
        R('160', 'explainer', 'for two colours the best constructions gave only about k·2^k'),
        R('160', 'known_before', 'Erdős 1980 survey'),
        R('160', 'known_before', 'Fox–Hunter (arXiv:2606.02541, June 2026) proved 3-color superexponential growth'),
        R('160', 'known_before', 'Campos–Fox–Schildkraut (arXiv:2608.20824, Aug 2026; the paper credits ChatGPT 5.6 Sol Pro with the coloring) proved W_2(k) >= (1-o(1)) k 2^{k-1}, settling W_2(k)/2^k -> infinity'),
        R('160', 'lean', 'k^{(1/100000)·k·Nat.log 2 r} < W r k'),
        R('160', 'caveats', 'the threshold K_0 ineffective/unspecified'),
    ]})
print('ok b1')
