import sys
R = [
("Scale by scale, a potential pays for each step of the recursion.", "Scale by scale, a two-depth potential pays for every step of the recursion."),
("Claimed: every exponent above three.", "Claimed: every exponent above three, for curved surfaces."),
("Claimed: the critical exponent, three.", "Claimed: any smoothing works at exponent three."),
("Bound growth for masses on lines, then transfer it to waves.", "First bound growth for masses moving on lines, then transfer it to waves."),
("Combine lossless estimates for crossing, sparse and paired packets.", "Combine lossless estimates for crossing, sparse and paired packets, then sum frequencies."),
("Claimed: the endpoint itself, one third.", "Claimed: the endpoint, one third in the plane."),
("At each smaller scale the distance from a plane shrinks.", "At each smaller scale, bounded pairings shrink the distance from a plane."),
("Claimed: bounded Riesz means rectifiable.", "Claimed: bounded Riesz transforms mean rectifiable sets."),
("Claimed: bounded, at short scales.", "Claimed: bounded, uniformly, at short scales."),
("Bound each frequency band, then glue the bands with a commutator.", "Bound each frequency band, then glue the bands back with a commutator."),
("Claimed for geometric sequences only.", "Claimed, but for geometric sequences only."),
("Random gaps, steered by coin flips, catch every copy at once.", "Random gaps, steered by a tree of coin flips, catch every copy at once."),
("Claimed: bounded distortion, a universal constant.", "Claimed: bounded distortion, by one universal constant."),
("Random cuts, mixed together, rebuild its distances.", "Random cuts, mixed together, rebuild all its distances."),
("Follow a path of blends; volume reduces to a variance inequality.", "Follow a path of blended bodies; volume reduces to a variance inequality."),
("Claimed: true for all symmetric bodies.", "Claimed: true for all origin-symmetric bodies, every dimension."),
("Claimed: one constant, in every dimension.", "Claimed: one constant, the same in every dimension."),
("Pick a clever random law for projections, then sample coordinates.", "Pick a clever random law for projections, then sample coordinates independently."),
("Claimed: a sub-polynomial number of coordinates.", "Claimed: far fewer coordinates, a sub-polynomial number."),
('"Dimension reduction beyond Euclid."', '"Dimension reduction beyond Euclidean space."'),
("Nest words level by level; the lag against cuts compounds.", "Nest words level by level; the lag against cuts compounds each time."),
("Claimed: the known embedding is optimal.", "Claimed: the old embedding is essentially optimal."),
("a tree-built space has no small quotient.", "a tree-built space has no small quotient at all."),
("Under one axiom, no; under another, yes.", "Under one axiom, no; under another, always yes."),
("Claimed: not necessarily, even separable ones.", "Claimed: not necessarily, even for separable spaces."),
("A matrix's 'numerical range' controls its polynomials up to a factor 2, even when the coefficients are matrices", "A matrix's 'numerical range' controls its polynomials up to a factor 2, even with matrix coefficients"),
("A rank-free decay of Walsh transforms rules out the copies.", "A decay of Walsh transforms, free of rank, rules out the uniform copies."),
("Without superreflexivity, walks travel in straight lines, breaking Markov type.", "Without superreflexivity, random walks travel in straight lines, breaking Markov type."),
("Claimed: Markov type forces superreflexivity.", "Claimed: nontrivial Markov type forces superreflexivity."),
("Claimed: yes, in every reflexive space.", "Claimed: yes, in every reflexive Banach space."),
("Rows far apart, columns easy to list: the counts split.", "Rows sit far apart, but the columns are easy to list: the counts split."),
("Claimed: approximation, but never bounded.", "Claimed: approximation works, but never with a bound."),
("Claimed: a reflexive counterexample.", "Claimed: a reflexive space where diamonds distort."),
("Charged particles steering themselves by their own fields: can one get kicked to infinite momentum in finite time?", "Charged particles steered by their own fields: can one be kicked to infinite momentum in finite time?"),
("Claimed: two distinct global solutions.", "Claimed: two distinct global solutions, one start."),
("Expand over whole clusters of interacting particles, not single collisions.", "Expand over whole clusters of interacting particles, not over single collisions."),
("Claimed: the same, for smooth potentials.", "Claimed: the same, for smooth stable potentials."),
("flattens every cone below seven.", "flattens every cone below dimension seven."),
("The critical dimension was five, six or seven.", "The critical dimension was known: five, six or seven."),
("deforms one body onto another. Smoothing", "deforms one body onto another, like rubber. Smoothing"),
("Rebuild the map patch by patch against a triangulation, then smooth.", "Rebuild the map patch by patch against a triangulation, then smooth the result."),
("Claimed: settled in three dimensions.", "Claimed: settled in three dimensions, the open case."),
("Claimed: true for smooth, hole-free plates.", "Claimed: true for every smooth, hole-free plate."),
("A virial identity bounds the energy; dilating breaks the bound.", "Assume a solution; a virial identity bounds its energy, and dilating breaks the bound."),
("Claimed: proved in every dimension.", "Claimed: no positive solution, in every dimension."),
("A flat-core profile, an exact spectrum, and a degree argument.", "Take a large power, certify the spectrum exactly, then use a degree argument."),
("Claimed: blowup on an open set.", "Claimed: blowup on an open set of data."),
("Three electrons spread like a smooth cloud: their best arrangement can't follow a fixed rule from one to the rest", "Three electrons in a smooth cloud: no rule fixing two of them from the first one is ever optimal"),
("Claimed: reaching the region is undecidable.", "Claimed: reaching the region is undecidable, in general."),
("Claimed: Hölder gradients, every dimension.", "Claimed: Hölder gradients in every dimension, three up."),
]
f = 'enrich.py'; s = open(f).read()
for a, b in R:
    n = s.count(a)
    if n != 1: print('COUNT', n, a)
    s = s.replace(a, b)
open(f, 'w').write(s)
