"use client"

import { useState } from "react"

import { cn } from "@/lib/utils"

// The single fix that keeps trillion-scale zero RL from collapsing: the
// training-inference ratio correction. Rollouts are generated by the *inference*
// engine (SGLang) but gradients come from the *training* engine (Megatron); their
// logits disagree by tiny floating-point amounts that the importance ratio
// amplifies until training diverges. Ring's fix: compute the ratio's NUMERATOR
// from the training engine, so it measures the update you actually make. Scrub the
// policy drift and flip between the naive ratio and the corrected one. Illustrative.

const ACCENT = "oklch(0.58 0.19 300)"
const WARN = "oklch(0.62 0.20 25)"
const N = 14
const CLIP = 5 // eps_high = 5.0, no lower bound
const YMAX = 6

// scene geometry
const W = 760
const H = 210
const MX = 46
const PLOT_T = 20
const PLOT_B = 176
const BW = 26
const GAP = (W - 2 * MX - N * BW) / (N - 1)
const bx = (i: number) => MX + i * (BW + GAP)
const yOf = (v: number) => PLOT_B - (Math.min(v, YMAX) / YMAX) * (PLOT_B - PLOT_T)

type Mode = "naive" | "corrected"

function ratios(mode: Mode, drift: number) {
  return Array.from({ length: N }, (_, i) => {
    const osc = Math.sin(i * 1.3 + 0.7)
    // the genuine, well-behaved update the training engine makes: stays near 1
    const corrected = Math.exp(0.22 * osc * drift)
    if (mode === "corrected") return corrected
    // the naive ratio: a per-token engine gap multiplies in and blows up with drift
    const gap = 0.5 + 0.5 * Math.cos(i * 1.9 + 0.3)
    return corrected * Math.exp(2.7 * gap * drift)
  })
}

export function RatioCorrection() {
  const [mode, setMode] = useState<Mode>("naive")
  const [drift, setDrift] = useState(70)

  const d = drift / 100
  const vals = ratios(mode, d)
  const clipped = vals.filter((v) => v > CLIP).length
  const maxV = Math.max(...vals)
  const collapsing = clipped >= 4
  const y1 = yOf(1)
  const yClip = yOf(CLIP)

  return (
    <figure className="my-8 overflow-hidden rounded-xl border bg-gradient-to-b from-muted/15 to-transparent">
      <div className="flex items-center justify-between border-b px-4 py-2.5 font-mono text-xs text-muted-foreground">
        <span>importance ratio ρ per token · clip at ε_high = 5</span>
        <span className="text-muted-foreground/50">illustrative</span>
      </div>

      <div className="p-3 sm:p-4">
        <svg viewBox={`0 0 ${W} ${H}`} className="w-full" role="img" aria-label={`Per-token importance ratios under the ${mode} scheme; ${clipped} of ${N} tokens exceed the clip threshold`}>
          <defs>
            <filter id="rz-ratio-soft" x="-40%" y="-40%" width="180%" height="180%">
              <feDropShadow dx="0" dy="1" stdDeviation="1.2" floodOpacity="0.14" />
            </filter>
          </defs>

          {/* y grid + labels */}
          {[0, 1, 2, 3, 4, 5, 6].map((t) => (
            <g key={t}>
              <line x1={MX} y1={yOf(t)} x2={W - MX} y2={yOf(t)} stroke="var(--border)" strokeWidth={1} opacity={t === 0 ? 0.6 : 0.25} />
              <text x={MX - 8} y={yOf(t) + 3} textAnchor="end" className="fill-muted-foreground/70 font-mono" fontSize={9}>{t}</text>
            </g>
          ))}

          {/* identity line ρ=1 */}
          <line x1={MX} y1={y1} x2={W - MX} y2={y1} stroke="var(--muted-foreground)" strokeWidth={1.2} strokeDasharray="2 3" opacity={0.7} />
          <text x={W - MX} y={y1 - 4} textAnchor="end" className="fill-muted-foreground font-mono" fontSize={9}>ρ = 1 (no change)</text>

          {/* clip band */}
          <line x1={MX} y1={yClip} x2={W - MX} y2={yClip} stroke={WARN} strokeWidth={1.2} strokeDasharray="4 3" opacity={0.85} />
          <text x={MX} y={yClip - 4} className="font-mono" fontSize={9} fill={WARN}>clip ceiling</text>

          {/* bars */}
          {vals.map((v, i) => {
            const over = v > CLIP
            const top = yOf(v)
            return (
              <g key={i}>
                <rect
                  x={bx(i)}
                  y={top}
                  width={BW}
                  height={PLOT_B - top}
                  rx={4}
                  fill={over ? WARN : ACCENT}
                  opacity={over ? 0.9 : 0.85}
                  filter={over ? "url(#rz-ratio-soft)" : undefined}
                  className="transition-all duration-200"
                />
                {over && (
                  <text x={bx(i) + BW / 2} y={top - 4} textAnchor="middle" className="font-mono" fontSize={9} fill={WARN}>
                    {v > YMAX ? "↑" : ""}
                  </text>
                )}
              </g>
            )
          })}
        </svg>

        {/* controls */}
        <div className="mt-1 flex flex-wrap items-center gap-x-5 gap-y-2">
          <div className="flex items-center gap-1.5">
            <span className="font-mono text-[10px] text-muted-foreground">numerator</span>
            {([["naive", "inference engine"], ["corrected", "training engine (ours)"]] as [Mode, string][]).map(([m, lbl]) => (
              <button
                key={m}
                type="button"
                onClick={() => setMode(m)}
                aria-pressed={mode === m}
                className={cn(
                  "cursor-pointer rounded-md px-2 py-1 font-mono text-[10px] transition-colors",
                  mode === m ? "text-background" : "bg-muted text-muted-foreground hover:text-foreground"
                )}
                style={mode === m ? { background: ACCENT } : undefined}
              >
                {lbl}
              </button>
            ))}
          </div>
          <div className="ml-auto font-mono text-[10px] text-muted-foreground">
            max ρ <span className="text-foreground">{maxV.toFixed(1)}</span> · clipped{" "}
            <span style={{ color: clipped ? WARN : ACCENT }}>{clipped}</span>/{N} ·{" "}
            <span style={{ color: collapsing ? WARN : ACCENT }}>{collapsing ? "training collapses" : "training stable"}</span>
          </div>
        </div>

        <div className="mt-3">
          <div className="mb-1 font-mono text-[10px] text-muted-foreground">policy drift (steps since rollout) — drag</div>
          <input
            type="range"
            min={0}
            max={100}
            value={drift}
            onChange={(e) => setDrift(Number(e.target.value))}
            className="w-full cursor-pointer accent-[oklch(0.58_0.19_300)]"
          />
        </div>

        <p className="mt-3 text-sm leading-6 text-muted-foreground">
          With the <span style={{ color: ACCENT }}>corrected</span> numerator the ratio stays pinned near 1 however far the
          policy drifts — the clip almost never fires, so every token keeps contributing gradient. With the{" "}
          <span style={{ color: WARN }}>naive</span> numerator the train/infer logit gap compounds into ratios far above the
          ε_high = 5 ceiling; those tokens are clipped to a constant, their gradient vanishes, and (in the paper&rsquo;s
          runs) training collapses. The ablation shows the naive ratio failing near step 800 and a clip-only patch only
          delaying collapse to ~2,700 steps, while the correction trains indefinitely.
        </p>
      </div>
    </figure>
  )
}
