"use client"

import { useState } from "react"

import { cn } from "@/lib/utils"

// What survives a worker, and what does not.
//
// The rule from the blog, stated about as strongly as a design doc ever states
// anything: after a worker returns, "the worker's execution context is
// discarded and never used as model context by the system again. Its changes to
// the environment remain, but the episode is the persistent representation of
// the work."
//
// There is no separate summarization pass. The worker system prompt says the
// final response should be a concise handoff, and the first model response with
// no tool calls IS the episode.

type Item = {
  what: string
  fate: "kept" | "dropped" | "sideways"
  detail: string
}

const ITEMS: Item[] = [
  { what: "worker execution context", fate: "dropped", detail: "Every tool call, every file it read, every retry, every dead end. Discarded when the worker returns and never used as model context again. This is the whole point: the expensive part of doing the work is also the part least worth carrying forward." },
  { what: "the episode", fate: "kept", detail: "The worker's final response — the first one it produces with no tool calls. Not a summary generated by a second pass, but the answer itself, written as a handoff because the system prompt told it to. It is appended to the thread and becomes the only durable record of what happened." },
  { what: "changes to the environment", fate: "sideways", detail: "Files written, packages installed, branches pushed. These persist, but they live outside nac's state — the runtime does not track them. That asymmetry is where the sharp edge is." },
  { what: "source episodes from other threads", fate: "dropped", detail: "Thread weaving resolves each named source thread to its most recent retained episode and feeds it to the worker as context. It influences the new episode but is never copied into the target thread's history — so a thread's history stays its own." },
]

const KEPT = "oklch(0.55 0.16 155)"
const DROP = "oklch(0.58 0.19 25)"
const SIDE = "oklch(0.68 0.13 85)"
const C: Record<string, string> = { kept: KEPT, dropped: DROP, sideways: SIDE }
const LABEL: Record<string, string> = { kept: "persists in nac", dropped: "discarded", sideways: "persists outside nac" }

export function ContextLifecycle() {
  const [sel, setSel] = useState(0)
  const it = ITEMS[sel]

  return (
    <figure className="my-8 overflow-hidden rounded-xl border bg-gradient-to-b from-muted/15 to-transparent">
      <div className="flex flex-wrap items-center justify-between gap-2 border-b px-4 py-2.5">
        <span className="font-mono text-xs text-muted-foreground">what a finished worker leaves behind</span>
        <span className="font-mono text-[10px] text-muted-foreground">no summarization pass</span>
      </div>

      <div className="p-3 sm:p-4">
        <div className="space-y-1">
          {ITEMS.map((x, i) => (
            <button
              key={x.what}
              type="button"
              onClick={() => setSel(i)}
              aria-pressed={i === sel}
              className={cn(
                "flex w-full cursor-pointer items-center gap-2 rounded-md border px-2 py-1.5 text-left transition-colors",
                i === sel ? "border-foreground/30 bg-muted/40" : "border-transparent hover:bg-muted/20",
              )}
            >
              <span className="inline-block h-2.5 w-2.5 shrink-0 rounded-sm" style={{ background: C[x.fate] }} />
              <span className="flex-1 truncate font-mono text-[11px] text-foreground">{x.what}</span>
              <span className="shrink-0 font-mono text-[9px]" style={{ color: C[x.fate] }}>
                {LABEL[x.fate]}
              </span>
            </button>
          ))}
        </div>

        <div className="mt-3 rounded-lg border bg-muted/20 px-3 py-2.5">
          <div className="font-mono text-[11px]" style={{ color: C[it.fate] }}>
            {it.what} — {LABEL[it.fate]}
          </div>
          <div className="mt-1 text-sm leading-6 text-muted-foreground">{it.detail}</div>
        </div>

        <div className="mt-2 rounded-lg border px-3 py-2.5" style={{ borderColor: SIDE }}>
          <div className="font-mono text-[11px]" style={{ color: SIDE }}>
            the gap between the two kinds of persistence
          </div>
          <div className="mt-1 text-sm leading-6 text-muted-foreground">
            Because environment changes persist and episodes only persist on success, a worker that edits files and
            then dies leaves the world ahead of the record. Arcee says so directly: worker failures are &ldquo;not
            transactional,&rdquo; and a returned error means &ldquo;the environment may have moved ahead of
            persistent history.&rdquo; Every system that separates durable state from a scratch context has this
            seam somewhere; it is worth more that they printed it than that they solved it.
          </div>
        </div>

        <p className="mt-4 text-sm leading-6 text-muted-foreground">
          The design is one sentence: separate <em>the temporary context needed to perform an action</em> from{" "}
          <em>the persistent state needed to continue a workstream</em>. Most harnesses put both in the same
          transcript and then fight the consequences with compaction. nac never merges them, so there is nothing to
          compact — the orchestrator only ever reads episodes, and the transcripts that produced them are gone by
          the time it plans again.
        </p>
      </div>
    </figure>
  )
}
