"use client"

// All 372 result families in one searchable table. The rows are generated by
// scripts in my scratch directory from the release (title, discipline, Lean
// page, principal manuscript path) and from the per-family review notes the
// reviewers wrote for this article (claim, significance, kind, caveat). Nothing
// is fetched at runtime. Significance is our judgment, not OpenAI's; Lean is
// what lean/docs and formalization.yaml say, never whether it was re-run.
//
// Dual-native: the article's prose covers every family by discipline; this
// table is the index.

import { useMemo, useState } from "react"

import { DISCIPLINES, FAMILIES, SECTION_ANCHORS } from "./catalogue-data"

const SIG = ["landmark", "major", "notable", "technical"] as const
const LEAN = ["main theorem", "partial", "none"] as const
const SIG_TONE = [
  "bg-orange-500/15 border-orange-500/50",
  "bg-blue-500/10 border-blue-500/40",
  "bg-emerald-600/10 border-emerald-600/40",
  "bg-muted border-border",
]
const LEAN_TONE = ["text-emerald-700 dark:text-emerald-400", "text-amber-700 dark:text-amber-400", "text-muted-foreground"]

const PAGE = 25

export function FamilyCatalogue({ only }: { only?: number[] } = {}) {
  const [q, setQ] = useState("")
  const [disc, setDisc] = useState(-1)
  const [sig, setSig] = useState(-1)
  const [lean, setLean] = useState(-1)
  const [open, setOpen] = useState<string | null>(null)
  const [limit, setLimit] = useState(PAGE)

  const rows = useMemo(() => {
    const needle = q.trim().toLowerCase()
    return FAMILIES.filter(
      (f) =>
        (!only || only.includes(f.d)) &&
        (disc < 0 || f.d === disc) &&
        (sig < 0 || f.s === sig) &&
        (lean < 0 || f.l === lean) &&
        (!needle ||
          f.id.includes(needle) ||
          f.t.toLowerCase().includes(needle) ||
          f.c.toLowerCase().includes(needle)),
    )
  }, [q, disc, sig, lean, only])

  const counts = SIG.map((_, i) => rows.filter((r) => r.s === i).length)

  return (
    <div className="my-8 rounded-lg border bg-muted/20 p-4">
      <div className="grid gap-2 sm:grid-cols-[1fr_auto_auto_auto]">
        <input
          type="search"
          value={q}
          onChange={(e) => {
            setQ(e.target.value)
            setLimit(PAGE)
          }}
          placeholder={only ? "search these families" : "search 372 families: zeta, Kakeya, 107…"}
          aria-label="Search families"
          className="w-full rounded-md border bg-background px-2 py-1 text-sm"
        />
        <select
          aria-label="Discipline"
          value={disc}
          onChange={(e) => {
            setDisc(Number(e.target.value))
            setLimit(PAGE)
          }}
          className="rounded-md border bg-background px-2 py-1 text-xs"
        >
          <option value={-1}>all disciplines</option>
          {DISCIPLINES.map((d, i) =>
            !only || only.includes(i) ? (
              <option key={d} value={i}>
                {d}
              </option>
            ) : null,
          )}
        </select>
        <select
          aria-label="Significance"
          value={sig}
          onChange={(e) => {
            setSig(Number(e.target.value))
            setLimit(PAGE)
          }}
          className="rounded-md border bg-background px-2 py-1 text-xs"
        >
          <option value={-1}>any significance</option>
          {SIG.map((s, i) => (
            <option key={s} value={i}>
              {s}
            </option>
          ))}
        </select>
        <select
          aria-label="Lean"
          value={lean}
          onChange={(e) => {
            setLean(Number(e.target.value))
            setLimit(PAGE)
          }}
          className="rounded-md border bg-background px-2 py-1 text-xs"
        >
          <option value={-1}>any Lean status</option>
          {LEAN.map((s, i) => (
            <option key={s} value={i}>
              Lean: {s}
            </option>
          ))}
        </select>
      </div>

      <div className="mt-2 font-mono text-[11px] text-muted-foreground">
        {rows.length} families &middot;{" "}
        {SIG.map((s, i) => `${counts[i]} ${s}`).join(" · ")}
      </div>

      <ul className="mt-3 divide-y rounded-md border bg-background/60">
        {rows.slice(0, limit).map((f) => {
          const isOpen = open === f.id
          return (
            <li key={f.id} className="px-3 py-2">
              <button
                type="button"
                aria-expanded={isOpen}
                onClick={() => setOpen(isOpen ? null : f.id)}
                className="grid w-full grid-cols-[2.5rem_1fr] gap-x-2 text-left sm:grid-cols-[2.5rem_1fr_auto]"
              >
                <span className="font-mono text-xs text-muted-foreground">{f.id}</span>
                <span className="text-sm leading-5">{f.t}</span>
                <span className="col-start-2 flex flex-wrap items-center gap-1.5 sm:col-start-3 sm:justify-end">
                  <span className={`rounded border px-1.5 font-mono text-[10px] ${SIG_TONE[f.s]}`}>{SIG[f.s]}</span>
                  <span className={`font-mono text-[10px] ${LEAN_TONE[f.l]}`}>
                    {f.l === 2 ? "no Lean" : `Lean: ${LEAN[f.l]}`}
                  </span>
                </span>
              </button>
              {isOpen ? (
                <div className="mt-2 grid gap-1 pl-[3rem] text-xs leading-5">
                  <p>{f.c}</p>
                  {f.v ? <p className="text-muted-foreground">Caveat: {f.v}</p> : null}
                  <p className="font-mono text-[11px] text-muted-foreground">
                    {DISCIPLINES[f.d]} &middot; {f.k} &middot;{" "}
                    <a className="underline" href={`#${SECTION_ANCHORS[f.d]}`}>
                      discipline section
                    </a>{" "}
                    &middot;{" "}
                    <a className="underline" href={`https://github.com/openai/math/blob/main/preprints/${f.p}`}>
                      manuscript
                    </a>
                  </p>
                </div>
              ) : null}
            </li>
          )
        })}
      </ul>
      {rows.length > limit ? (
        <button
          type="button"
          onClick={() => setLimit(limit + 50)}
          className="mt-2 rounded-md border px-3 py-1 text-xs hover:bg-background"
        >
          show {Math.min(50, rows.length - limit)} more of {rows.length - limit}
        </button>
      ) : null}
    </div>
  )
}
