import os as _o, sys as _s; _s.path.insert(0, _o.path.dirname(_o.path.dirname(_o.path.abspath(__file__))) if _o.path.basename(_o.path.dirname(_o.path.abspath(__file__))) != 'generators' else _o.path.dirname(_o.path.abspath(__file__))); from _paths import GEN, REPO, OUT as _OUT, REVIEWS as _REV  # repo-relative paths (generators/_paths.py)
import json
import sys as _sys; _sys.path.insert(0, GEN); from enrich_ag import enrich
OUT=_OUT + '/'
AG="Algebraic and complex geometry"
def S(ref,q): return {"ref":ref,"quote":q}
def spec(id,kind,short,title,sub,obj,ach,lean,detail,ours,sources):
    s={"$schema":"../../brand-crew/skills/math-reels/schema.json","id":id,"discipline":AG,"kind":kind,"short":short,
       "title":{"title":title,"subtitle":sub},"object":obj,"achievement":ach,
       "verify":{"lean":lean,"detail":detail,"ourCheck":ours},"sources":sources}
    s=enrich(s)
    json.dump(s,open(OUT+id+'.json','w'),indent=1,ensure_ascii=False)
B=lambda *xs:[{"at":a,"text":t} for a,t in xs]
NOREAD="We read the claim and caveats; we did not check the proof"

spec("052","proof",r"Split tangent bundles are products",
 r"A split tangent bundle makes the universal cover a product",
 r"Claim: if $T_X = E_1 \oplus E_2$ with both summands integrable, the universal cover of $X$ is a product",
 {"dur":8,"layout":"sequence","panels":[
   {"primitive":"grid","until":4.2,"rows":4,"cols":6,
    "cells":[[0,0],[0,1],[0,2],[1,0],[1,1],[1,2]],
    "blocks":[{"r":0,"c":0,"h":2,"w":3,"label":"one product chart"}],
    "caption":"rows: leaves of $E_1$, columns: leaves of $E_2$ (schematic)"},
   {"primitive":"equation","from":4.2,"lines":[
     {"tex":r"T_X = E_1 \oplus E_2","tone":"soft","at":0.3},
     {"tex":r"\tilde X \;\cong\; \hl{X_1} \times \hl{X_2}","tone":"ink","at":1.1,"size":48}]}],
  "beats":B((0.2,"Locally, two foliations give product charts: Frobenius"),
            (2.8,"The hard part is continuing the charts globally, box by box"),
            (5.2,"Claimed: globally, the universal cover splits as a product"))},
 {"form":"status","label":"Beauville's splitting conjecture (2000), two summands",
  "statement":[r"T_X = E_1 \oplus E_2 \;\Rightarrow\; \tilde X \cong X_1 \times X_2"],
  "context":"Before: surfaces, threefolds and special classes (Brunella–Pereira–Touzet, Höring)",
  "stamp":"proved","note":"Two integrable summands only; Beauville allows any number"},
 "main","Formalized on custom complex-manifold foundations, worth an audit",
 "We read the Lean scope notes; we did not build the Lean",
 [S("review 052, known_before","Beauville ('Complex manifolds with split tangent bundle', 2000) conjectured universal-cover splitting"),
  S("review 052, caveats","Beauville's full conjecture allows any number of summands and does not assume integrability"),
  S("article, Tangent bundle splittings (family 052)","It is formalized (`OAI/Geometry/KahlerSplitting/Main.lean:14`), on custom complex-manifold foundations.")])

spec("053","counterexample",r"Pixton's completeness fails in Chow",
 r"A counterexample to Pixton's completeness conjecture",
 r"Claim: a tautological class outside the span of Pixton's relations vanishes in Chow and in cohomology",
 {"dur":8,"primitive":"equation","mode":"replace","lines":[
      {"tex": r"\overline{\mathcal M}_{g,n}", "note": "the moduli space of stable curves", "at": 0.3},
      {"tex": r"g = \term{g}{10^{60}}", "tone": "accent", "note": "the genus of the counterexample", "at": 2.9, "size": 60, "terms": {"g": {"label": "a one and sixty zeros", "tone": "hot", "at": 0.6, "visual": {"kind": "dots", "n": 60, "w": 220, "h": 70, "illustrative": False, "label": "one dot per zero"}}}},
      {"tex": r"n = 3\binom{10^{60}}{3}", "tone": "accent", "note": "the number of marked points", "at": 5.4, "size": 52}],
  "beats":B((0.2,"Pixton's relations hold among tautological classes; are they all of them?"),
            (2.8,"The claimed counterexample lives in genus $10^{60}$"),
            (5.3,"No computer can check an example this large; it rests on the proof"))},
 {"form":"status","label":"Pixton's completeness conjecture (2012)",
  "statement":[r"\langle \text{Pixton's relations} \rangle \ne \text{all tautological relations}"],
  "context":"Before: the relations were proved valid (Pandharipande–Pixton–Zvonkine 2015; Janda 2017)",
  "stamp":"disproved","note":"Only Pixton's original system; extended relation systems may survive"},
 "none","No Lean; the 61-page proof is the only check",NOREAD,
 [S("review 053, claim","the example has genus 10^60 and 3·C(10^60,3) markings"),
  S("review 053, known_before","Pixton (2012) proposed the graph-formula relations and conjectured they generate all tautological relations; validity proved in cohomology by Pandharipande–Pixton–Zvonkine (JAMS 2015) and in Chow by Janda (2017)"),
  S("review 053, caveats","61 pp; no Lean"),
  S("article, Pixton's completeness fails (family 053)","Extended relation systems may survive.")])

spec("054","counterexample",r"Irrational cubic fourfolds with a K3",
 r"Cubic fourfolds with a K3 category that are still irrational",
 r"Claim: a very general cubic in $\mathcal C_d$, $d$ large, is irrational though it has a K3 category",
 {"dur":8.2,"primitive":"venn",
  "sets":[{"label":"geometric K3 category"},{"label":"associated K3 (Hodge)"},{"label":"rational"}],
  "regions":[{"set":"A&B&C","tone":"ok","at":1.8},{"set":"A&B&!C","label":"claimed","tone":"hot","x":0.5,"y":0.27,"at":3.0}],
  "beats":B((0.2,"Kuznetsov: a cubic fourfold is rational exactly when its K3 category is geometric"),
            (2.9,"Known rational cubics, such as those on $\\mathcal C_{26}$, sit in the middle (schematic)"),
            (5.6,"The claim: very general cubics on most $\\mathcal C_d$ fill the region the conjecture empties"))},
 {"form":"status","label":"Kuznetsov's rationality conjecture (2010)",
  "statement":[r"\mathrm{Ku}(X) \cong D^b(S) \;\not\Rightarrow\; X \text{ rational}"],
  "context":"Before: no cubic fourfold was even known to be irrational until 2025",
  "stamp":"disproved","note":"Only for $d$ above an ineffective threshold $d_0$"},
 "none","No Lean; 62 pages, building on brand-new 2025 work on Hodge atoms",NOREAD,
 [S("article, Kuznetsov's rationality conjecture fails (family 054)","Until 2025 no cubic fourfold was even known to be irrational."),
  S("article, Kuznetsov's rationality conjecture fails (family 054)","Rational cubics do exist on $\\mathcal C_{26}$, $\\mathcal C_{38}$ and $\\mathcal C_{42}$ (Russo–Staglianò)"),
  S("review 054, known_before","Kuznetsov's conjecture (Kuznetsov 2010)"),
  S("review 054, known_before","'Birational invariants from Hodge structures and quantum multiplication', 2025/26"),
  S("review 054, caveats","62 pp; no Lean")])

spec("055","proof",r"Gepner stability on the quintic",
 r"Toda's Gepner point on every quintic threefold",
 r"Claim: a Bridgeland stability condition whose phases shift by exactly $2/5$ under the Gepner autoequivalence",
 {"dur":8,"primitive":"numberline","min":-0.15,"max":1.15,"y":0.6,
  "ticks":[0,{"v":0.4,"label":"$2/5$"},1],"axisLabel":"phase of a stable object",
  "markers":[{"v":0,"label":"$\\phi$","note":"a stable object","at":0.6}],
  "slide":{"from":0,"to":0.4,"at":2.8,"dur":1.6,"label":"$\\phi + 2/5$","note":"after the autoequivalence","derived":"2/5"},
  "beats":B((0.2,"A stability condition gives every stable object a phase"),
            (2.7,"Apply $T_{\\mathcal O} \\circ (-\\otimes \\mathcal O(1))$: every phase moves by the same amount"),
            (5.4,"The claim: exactly $2/5$, on every smooth quintic"))},
 {"form":"status","label":"Toda's Gepner conjecture (2014)",
  "statement":[r"T_{\mathcal O}\circ(-\otimes\mathcal O(1)) \text{ shifts phases by } \tfrac{2}{5}"],
  "context":"Before: Chunyi Li built large-volume stability on the quintic (2019); the Gepner point was open",
  "stamp":"proved","note":"Also large-volume stability on every Calabi–Yau threefold"},
 "none","No Lean; 71 pages in total",NOREAD,
 [S("review 055, known_before","Chunyi Li (Invent. Math. 2019) for the quintic (large volume)"),
  S("review 055, known_before","Toda's Gepner conjecture (Toda 2014 via matrix factorizations) open"),
  S("review 055, claim","shifts phases by exactly 2/5"),
  S("review 055, caveats","71 pp total; no Lean")])

spec("056","proof",r"Flips terminate on fourfolds",
 r"Every log canonical MMP on a fourfold terminates",
 r"Claim: every sequence of log canonical flips on a projective fourfold stops, with Kähler analogues",
 {"dur":8,"primitive":"sequence",
  "items":["$X_0$","$X_1$","$X_2$","$X_3$","$X_4$","$X_5$","$X_6$","$X_N$"],
  "marks":{"7":{"tone":"accent","at":3.6}},"at":0.4,"stagger":0.3,
  "caption":"each step is a flip $X_i \\dashrightarrow X_{i+1}$ (schematic)",
  "beats":B((0.2,"The minimal model program improves a variety one flip at a time"),
            (2.9,"Termination: no chain of flips can go on forever"),
            (5.4,"Claimed for log canonical fourfolds with rational boundary"))},
 {"form":"status","label":"Termination of flips in dimension 4",
  "statement":[r"X_0 \dashrightarrow X_1 \dashrightarrow \cdots \dashrightarrow X_N \text{ stops}"],
  "context":"Before: terminal and canonical fourfolds (Shokurov 2004), klt with scaling (Alexeev–Hacon–Kawamata 2007)",
  "stamp":"proved","note":"The Kähler results cover existing flip sequences only"},
 "none","No Lean; 231 pages, and two manuscripts share one title",NOREAD,
 [S("review 056, known_before","Shokurov (2004) terminal/canonical 4-folds; Alexeev–Hacon–Kawamata (Invent. Math. 2007)"),
  S("review 056, caveats","231 pp; no Lean"),
  S("article, Termination of flips on fourfolds (family 056)","Two manuscripts share the title")])

spec("057","proof",r"Campana's abelianity conjecture",
 r"Special Kähler manifolds have virtually abelian $\pi_1$",
 r"Claim: every special compact Kähler manifold has a virtually abelian fundamental group",
 {"dur":8,"primitive":"venn",
  "sets":[{"label":"special compact Kähler"},{"label":"virtually abelian $\\pi_1$"}],
  "regions":[{"set":"A&!B","label":"claimed empty","tone":"bad","x":0.33,"y":0.5,"at":3.0}],
  "members":[{"x":0.5,"y":0.42,"label":"tori","at":1.8},{"x":0.5,"y":0.58,"label":"$\\kappa = 0$","at":5.4}],
  "beats":B((0.2,"Special: no fibration onto an orbifold of general type (schematic)"),
            (2.9,"Campana: no special manifold sits outside the virtually abelian set"),
            (5.3,"So every compact Kähler manifold with $\\kappa = 0$ would have virtually abelian $\\pi_1$"))},
 {"form":"status","label":"Campana's abelianity conjecture (2004)",
  "statement":[r"X \text{ special} \;\Rightarrow\; \pi_1(X) \text{ virtually abelian}"],
  "context":"Before: known only for linear representations of $\\pi_1$",
  "stamp":"proved","note":"Cites the release's own Shafarevich counterexample (family 046)"},
 "none","No Lean; the proof uses $L^2$ Dolbeault spectral analysis on the universal cover",NOREAD,
 [S("review 057, known_before","Campana's conjecture (Campana, Ann. Inst. Fourier 2004"),
  S("review 057, caveats","057_0 cites the release's Shafarevich counterexample paper (046)")])

spec("058","proof",r"Kollár–Pardon: semialgebraic covers",
 r"Semialgebraic universal covers are $D \times \mathbb{C}^m \times F$",
 r"Claim: a universal cover is semialgebraic exactly when it is a symmetric domain times $\mathbb{C}^m$ times $F$",
 {"dur":8,"primitive":"equation","lines":[
      {"tex": r"\tilde X \;\cong\; \term{d}{D} \;\times\; \term{c}{\mathbb{C}^m} \;\times\; \term{f}{F}", "at": 0.4, "size": 56, "y": 0.18, "terms": {"d": {"label": "symmetric domain", "tone": "accent", "at": 1.0, "visual": {"kind": "shape", "shape": "circle", "fill": True, "dx": -150, "w": 120, "h": 80}}, "c": {"label": "flat space", "tone": "cool", "at": 1.7, "visual": {"kind": "shape", "shape": "superellipse", "p": 8, "w": 120, "h": 80}}, "f": {"label": "compact piece", "tone": "warn", "at": 2.4, "visual": {"kind": "shape", "shape": "regular", "n": 5, "dx": 150, "w": 120, "h": 80}}}},
      {"tex": r"\tilde X \text{ semialgebraic} \iff \text{it is such a product}", "tone": "soft", "at": 4.4, "size": 30, "y": 0.88}],
  "beats":B((0.2,"When can a universal cover be cut out by real polynomial inequalities?"),
            (2.8,"Kollár–Pardon: only for these products"),
            (5.4,"The bounded-domain half extends Frankel's theorem from convex to semialgebraic"))},
 {"form":"status","label":"Kollár–Pardon conjecture (2012)",
  "statement":[r"\tilde X \text{ semialgebraic} \iff \tilde X \cong D \times \mathbb{C}^m \times F"],
  "context":"Before: Frankel (1989) did bounded convex domains with compact quotient",
  "stamp":"proved","note":"The classification uses the release's own abundance and abelianity papers"},
 "part","Lean has only the bounded-domain half, on self-contained definitions","We read the Lean scope notes; we did not build the Lean",
 [S("review 058, known_before","Kollár–Pardon (Math. Res. Lett. 2012"),
  S("review 058, known_before","Frankel (Acta 1989) proved bounded convex domains with compact quotient are symmetric"),
  S("article, Kollár–Pardon (family 058)","The classification uses the release's abundance and abelianity papers.")])

spec("059","counterexample",r"Zariski's multiplicity question: no",
 r"Same embedded topology, different multiplicity",
 r"Claim: hypersurface germs that are ambiently homeomorphic with multiplicities 2 and 3, and 4 and 5",
 {"dur":8.2,"primitive":"numberline","min":0.5,"max":6,"y":0.5,"ticks":[1,2,3,4,5],
  "axisLabel":"multiplicity: lowest degree of the equation",
  "markers":[{"v":2,"label":"$f_2$","at":0.6},{"v":3,"label":"$f_3$","at":0.9},
             {"v":4,"label":"$f_4$","at":1.2,"tone":"claim"},{"v":5,"label":"$f_5$","at":1.5,"tone":"claim"}],
  "ranges":[{"from":2,"to":3,"label":"homeomorphic","note":"in $\\mathbb{C}^N$, $8 \\mid N$","side":"below","at":3.0,"tone":"hot"},
            {"from":4,"to":5,"label":"homeomorphic","note":"in $\\mathbb{C}^4$","side":"below","at":3.6,"tone":"hot"}],
  "beats":B((0.2,"Zariski asked: does the embedded topology of a singularity fix its multiplicity?"),
            (2.9,"Claimed: two pairs of germs with the same topology and different multiplicities"),
            (5.5,"The method: different lowest degrees, congruent Seifert forms"))},
 {"form":"status","label":"Zariski's multiplicity question (1971)",
  "statement":[r"\text{embedded topology of } f^{-1}(0) \;\not\Rightarrow\; \operatorname{mult}(f)"],
  "context":"Before: true for plane curves and for multiplicity 1 (A'Campo, Lê), widely believed true",
  "stamp":"counterexample","note":"Surfaces in $\\mathbb{C}^3$ are not covered"},
 "none","No Lean; the topology rests on a surgery-theoretic classification",NOREAD,
 [S("article, Zariski's multiplicity question fails (family 059)","Zariski asked in 1971 whether the embedded topology of a hypersurface singularity determines its multiplicity."),
  S("article, Zariski's multiplicity question fails (family 059)","It is true for plane curves and for multiplicity 1 (A'Campo, Lê)"),
  S("review 059, claim","multiplicities 2 and 3"),
  S("review 059, claim","multiplicities 4 and 5")])

spec("060","proof",r"The global spherical shell conjecture",
 r"Every minimal class VII surface with $b_2 > 0$ has a shell",
 r"Claim: every minimal class VII surface with $b_2 > 0$ contains a global spherical shell",
 {"dur":8,"primitive":"sequence","items":["1","2","3","4","5","6","7","8"],"ellipsis":True,
  "index":"$b_2$","at":0.4,"stagger":0.12,
  "marks":{"0":{"tone":"cool","at":2.9},"1":{"tone":"cool","at":3.1},
           "2":{"tone":"accent","at":5.4},"3":{"tone":"accent","at":5.5},"4":{"tone":"accent","at":5.6},
           "5":{"tone":"accent","at":5.7},"6":{"tone":"accent","at":5.8},"7":{"tone":"accent","at":5.9}},
  "caption":"second Betti number $b_2$ of a minimal class VII surface",
  "beats":B((0.2,"Class VII surfaces: the last unclassified piece of the Kodaira classification"),
            (2.8,"Teleman proved $b_2 = 1$ (2005) and $b_2 = 2$ (2010) with gauge theory"),
            (5.3,"The claim covers every $b_2 > 0$ in one uniform argument"))},
 {"form":"status","label":"Nakamura's global spherical shell conjecture",
  "statement":[r"b_2(X) > 0 \;\Rightarrow\; X \cong_{\text{diff}} (S^1\times S^3)\,\#\, b_2\,\overline{\mathbb{CP}}^2"],
  "context":"Before: $b_2 = 1$ and $b_2 = 2$ by Teleman; general $b_2$ open",
  "stamp":"proved","note":"If it holds, minimal class VII surfaces with $b_2 > 0$ are classified"},
 "none","No Lean; a uniform 39-page proof where Teleman needed case-specific work",NOREAD,
 [S("review 060, known_before","b2 = 1 by Teleman (Invent. Math. 2005), b2 = 2 by Teleman (Annals 2010)"),
  S("article, The global spherical shell conjecture (family 060)","The paper claims all $b_2>0$ in 39 pages")])

spec("062","proof",r"The LeBrun–Salamon conjecture",
 r"Every contact Fano manifold is an adjoint variety",
 r"Claim: every projective contact Fano manifold is homogeneous, so positive quaternion-Kähler means Wolf space",
 {"dur":8,"primitive":"equation","lines":[
      {"tex": "M \\;\\text{positive quaternion-K\\\"ahler}", "tone": "soft", "at": 0.4, "size": 34, "y": 0.05},
      {"tex": r"\term{z}{Z(M)} \;\text{twistor space: contact Fano}", "tone": "soft", "at": 2.8, "size": 34, "y": 0.3, "terms": {"z": {"label": "built from $M$", "tone": "cool", "at": 0.6}}},
      {"tex": r"Z \cong \term{a}{\text{adjoint variety of a simple Lie algebra}}", "at": 5.2, "size": 34, "y": 0.56, "terms": {"a": {"label": "homogeneous: symmetric everywhere", "tone": "accent", "at": 0.7, "visual": {"kind": "shape", "shape": "regular", "n": 6, "w": 110, "h": 80}}}}],
  "beats":B((0.2,"Start from a positive quaternion-Kähler manifold $M$"),
            (2.7,"Its twistor space is a contact Fano manifold"),
            (5.1,"Claimed: that is always homogeneous, so $M$ is a symmetric Wolf space"))},
 {"form":"status","label":"LeBrun–Salamon conjecture (1994)",
  "statement":[r"M \text{ positive quaternion-K\"ahler} \;\Rightarrow\; M \text{ a Wolf space}"],
  "context":"Before: known in real dimensions 8 and 12, and somewhat further by torus actions",
  "stamp":"proved","note":"Also a classification of projective contact manifolds"},
 "none","No Lean; 40 pages, a single paper",NOREAD,
 [S("article, The LeBrun–Salamon conjecture (family 062)","LeBrun and Salamon conjectured in 1994"),
  S("article, The LeBrun–Salamon conjecture (family 062)","It was known in real dimensions 8 and 12 and pushed somewhat further by torus-action methods."),
  S("article, The LeBrun–Salamon conjecture (family 062)","40 pages, no Lean.")])

spec("063","proof",r"The generalized Mukai conjecture",
 r"The generalized Mukai conjecture for Fano manifolds",
 r"Claim: every Fano manifold has $\rho(\iota-1) \le n$, with equality only for $(\mathbb{P}^{\iota-1})^\rho$",
 {"dur":8,"primitive":"equation","lines":[
      {"tex": r"\term{r}{\rho}\,(\term{i}{\iota} - 1) \;\le\; \term{n}{n}", "tone": "accent", "at": 0.4, "size": 60, "y": 0.22, "terms": {"r": {"label": "independent directions", "tone": "cool", "at": 0.7, "side": "above"}, "i": {"label": "its lightest curve's weight", "tone": "warn", "at": 1.5}, "n": {"label": "dimension", "tone": "ok", "at": 2.3, "side": "above"}}},
      {"tex": r"(\mathbb{P}^2)^3:\ \rho = 3,\ \iota = 3,\ 3 \cdot 2 = 6 = n", "tone": "hot", "at": 4.6, "size": 34, "y": 0.74}],
  "beats":B((0.2,"Heavy rational curves leave room for only a few independent directions"),
            (4.5,"Products of projective spaces sit exactly on the bound"))},
 {"form":"status","label":"Generalized Mukai conjecture (2003)",
  "statement":[r"\rho(\iota-1) \le n,\ \text{equality iff } X \cong (\mathbb{P}^{\iota-1})^{\rho}"],
  "context":"Before: known up to dimension 5, for toric Fano manifolds and for large pseudoindex",
  "stamp":"proved","note":"A short Gromov–Witten proof, 19 pages, unrefereed"},
 "none","No Lean; the proof runs through eigenvalues of quantum multiplication",NOREAD,
 [S("review 063, known_before","generalized by Bonavero–Casagrande–Debarre–Druel (2003)"),
  S("article, The generalized Mukai conjecture (family 063)","It was known up to dimension 5."),
  S("article, The generalized Mukai conjecture (family 063)","The proof is a 19-page Gromov–Witten argument")])

spec("064","proof",r"$\mu$-constant surface singularities",
 r"Constant Milnor number means constant topology, in $\mathbb{C}^3$",
 r"Claim: every $\mu$-constant family of isolated surface singularities in $\mathbb{C}^3$ is topologically trivial",
 {"dur":8,"layout":"sequence","panels":[
   {"primitive":"plot","until":4.4,"x":[0,1],"y":[0,2],"xticks":[0,1],"yticks":[{"v":1,"label":"$\\mu_0$"}],
    "xlabel":"family parameter $t$","ylabel":"Milnor number $\\mu(f_t)$",
    "curves":[{"f":"1","label":"$\\mu(f_t) = \\mu_0$","at":0.6,"dur":1.6}]},
   {"primitive":"equation","from":4.4,"lines":[
     {"tex":r"f_t \circ \varphi_t = f_0","tone":"accent","at":0.3,"size":56},
     {"tex":r"\varphi_t \text{ homeomorphisms, continuous in } t","tone":"soft","at":1.0,"size":30}]}],
  "beats":B((0.2,"A family $f_t$ of singularities in $\\mathbb{C}^3$ whose Milnor number never changes"),
            (2.8,"Lê–Ramanujam settled every other dimension; surfaces were the gap"),
            (5.0,"Claimed: homeomorphisms carry each $f_t$ back to $f_0$"))},
 {"form":"status","label":"Lê–Ramanujam problem for surfaces (1976)",
  "statement":[r"\mu(f_t) \text{ constant} \;\Rightarrow\; f_t\circ\varphi_t = f_0"],
  "context":"Before: Lê–Ramanujam (1976) proved $n \\ne 3$ by h-cobordism; surfaces in $\\mathbb{C}^3$ were open",
  "stamp":"proved","note":"Surfaces in $\\mathbb{C}^3$ were the one remaining case"},
 "none","No Lean; 37 pages",NOREAD,
 [S("review 064, known_before","Lê–Ramanujam (Amer. J. Math. 1976) proved topological triviality of μ-constant families for n ≠ 3"),
  S("review 064, caveats","Surface case only (the remaining case). 37 pp. No Lean.")])

spec("065","proof",r"Virasoro constraints, complete intersections",
 r"Virasoro constraints for every complete intersection",
 r"Claim: the full descendant Virasoro conjecture for every smooth complete intersection, no semisimplicity",
 {"dur":8,"primitive":"equation","lines":[
      {"tex": r"\term{z}{Z_X} = \exp\Big(\textstyle\sum_{g} \hbar^{g-1} \term{f}{F_g}\Big)", "tone": "soft", "at": 0.4, "size": 40, "y": 0.1, "terms": {"z": {"label": "all curve counts", "tone": "cool", "at": 0.7}, "f": {"label": "genus $g$", "tone": "warn", "at": 1.3}}},
      {"tex": r"\term{l}{L_k}\, Z_X = \term{o}{0}\qquad k \ge -1", "tone": "ink", "at": 2.8, "size": 48, "y": 0.48, "terms": {"l": {"label": "differential operators", "tone": "accent", "at": 0.6}, "o": {"label": "kill it", "tone": "ok", "mark": "box", "at": 1.3}}},
      {"tex": r"[L_m, L_n] = (m-n)\,L_{m+n}", "tone": "soft", "at": 5.2, "size": 30, "y": 0.86}],
  "beats":B((0.2,"$Z_X$ packs every Gromov–Witten invariant of $X$, in all genera"),
            (2.7,"The conjecture: infinitely many differential equations annihilate it"),
            (5.1,"Claimed for complete intersections, including odd and primitive classes"))},
 {"form":"status","label":"Virasoro conjecture (Eguchi–Hori–Xiong, 1997)",
  "statement":[r"L_k Z_X = 0 \text{ for every smooth complete intersection } X"],
  "context":"Before: $\\mathbb{P}^1$ (Okounkov–Pandharipande 2006) and semisimple targets (Givental 2001; Teleman 2012)",
  "stamp":"proved","note":"A companion passes the constraints to projective bundles"},
 "none","No Lean; the projective-bundle companion is conditional by design",NOREAD,
 [S("review 065, known_before","Eguchi–Hori–Xiong (1997) Virasoro conjecture; proved for P¹ (Okounkov–Pandharipande 2006), toric/semisimple (Givental 2001; Teleman 2012 for semisimple)")])

spec("066","proof",r"Bounded klt complements",
 r"Bounded klt complements for Fano contractions",
 r"Claim: every $\varepsilon$-lc Fano contraction has klt complements of index bounded by $d$ and $\varepsilon$",
 {"dur":8,"primitive":"equation","lines":[
      {"tex": r"f\colon X \to Z \quad \varepsilon\text{-lc Fano contraction},\ \dim X = d", "tone": "soft", "at": 0.4, "size": 30, "y": 0.05},
      {"tex": r"\exists\, B^+ \ge B:\quad \term{n}{N}(K_X + B^+) \sim 0 \text{ near } z", "tone": "ink", "at": 2.8, "size": 38, "y": 0.32, "terms": {"n": {"label": "the index", "tone": "warn", "at": 0.6}}},
      {"tex": r"(X, B^+)\ \text{klt},\qquad \term{q}{N \le N(d,\varepsilon)}", "tone": "ink", "at": 4.4, "size": 38, "y": 0.62, "terms": {"q": {"label": r"bounded by $d$ and $\varepsilon$ alone", "tone": "accent", "mark": "box", "at": 0.6}}}],
  "beats":B((0.2,"A complement makes a Fano-type fibration Calabi–Yau-like near a point"),
            (2.7,"Its index $N$ says how far you must scale before it closes up"),
            (5.2,"Claimed: klt complements with $N$ bounded by $d$ and $\\varepsilon$ alone"))},
 {"form":"status","label":"Shokurov's bounded klt complements conjecture",
  "statement":[r"N(K_X+B^+) \sim 0,\ (X,B^+) \text{ klt},\ N \le N(d,\varepsilon)"],
  "context":"Before: Birkar (2019) bounded lc complements and proved BAB; klt complements were open",
  "stamp":"proved","note":"Finite rational coefficients only; also Birkar–Shokurov's Cartier conjecture"},
 "none","No Lean; 199 pages in two papers",NOREAD,
 [S("review 066, known_before","Birkar (Annals 2019, 'Anti-pluricanonical systems on Fano varieties') proved boundedness of (lc) complements and BAB; bounded klt complements conjecture open"),
  S("review 066, caveats","199 pp in two papers. No Lean.")])

spec("067","partial",r"Campana–Peternell in dimension 6",
 r"The Campana–Peternell conjecture in dimension six",
 r"Claim: every smooth Fano sixfold with nef tangent bundle is rational homogeneous",
 {"dur":8,"primitive":"sequence","items":["1","2","3","4","5","6","7","8"],"ellipsis":True,
  "index":"dim","at":0.4,"stagger":0.12,
  "marks":{"0":{"tone":"cool","at":2.9},"1":{"tone":"cool","at":3.0},"2":{"tone":"cool","at":3.1},
           "3":{"tone":"cool","at":3.2},"4":{"tone":"cool","at":3.3},"5":{"tone":"accent","at":5.4}},
  "caption":"dimension of a Fano manifold with nef tangent bundle",
  "beats":B((0.2,"Conjecture: Fano manifolds with nef tangent bundle are rational homogeneous"),
            (2.8,"Known up to dimension 5 (Campana–Peternell, Mok, Watanabe 2014)"),
            (5.3,"The claim adds dimension 6; dimension 7 and up stay open"))},
 {"form":"status","label":"Campana–Peternell conjecture (1991), dimension 6",
  "statement":[r"X \text{ Fano},\ T_X \text{ nef},\ \dim X = 6", r"\Longrightarrow\; X \text{ rational homogeneous}"],
  "context":"Before: dimensions up to 5; the general conjecture stays open",
  "stamp":"partial","note":"Ends with an exact arithmetic certificate (Appendix A)"},
 "none","No Lean; 27 pages with a computer-checkable appendix",NOREAD,
 [S("review 067, known_before","Campana–Peternell (1991)"),
  S("review 067, known_before","dim 5 (Watanabe 2014; Kanemitsu)"),
  S("review 067, caveats","27 pp; no Lean")])

spec("068","proof",r"Anticanonical nonvanishing",
 r"Anticanonical nonvanishing in every dimension",
 r"Claim: if $-K_X$ carries a smooth semipositive metric, some power $-mK_X$ has a section",
 {"dur":8,"heading":"The main theorem and the papers it rests on (schematic)","primitive":"tree","at":0.4,
  "nodes":[{"id":"r","label":"$H^0(X,-mK_X) \\ne 0$"},
           {"id":"a","label":"index polynomiality","parent":"r","status":"paper"},
           {"id":"b","label":"metric descent","parent":"r","status":"paper"},
           {"id":"c","label":"cohomological transfer","parent":"r","status":"paper"},
           {"id":"d","label":"integrable metrics","parent":"r","status":"paper"},
           {"id":"e","label":"structure theorem","parent":"r","status":"prior"}],
  "beats":B((0.2,"Seven papers form one chain; several are stated reductions"),
            (3.4,"The structure theorem splits the universal cover; torus actions are the hard part"))},
 {"form":"status","label":"Yau's problem: anticanonical nonvanishing",
  "statement":[r"-K_X \text{ smooth semipositive}", r"\Longrightarrow\; H^0(X,-mK_X) \ne 0 \text{ for some } m > 0"],
  "context":"Before: structure theorems (Cao–Höring 2019); for merely nef $-K_X$ it is false",
  "stamp":"proved","note":"Seven manuscripts, 270 pages, several of them reductions"},
 "none","No Lean; the whole chain is paper-only",NOREAD,
 [S("review 068, known_before","Cao–Höring (2019 structure theorem)"),
  S("review 068, known_before","Nonvanishing for nef −K is false in general"),
  S("review 068, caveats","Seven manuscripts (270 pp) form one chain")])

spec("069","proof",r"Quantum geometric Langlands, $c \notin \mathbb{Q}$",
 r"Quantum geometric Langlands at irrational level",
 r"Claim: $D_c(\mathrm{Bun}_G) \simeq D_{-1/(rc)}(\mathrm{Bun}_{G^\vee})$ for every simple $G$, curve and $c \notin \mathbb{Q}$",
 {"dur":8.2,"layout":"sequence","panels":[
   {"primitive":"numberline","until":4.2,"min":-0.25,"max":2.25,"y":0.55,"ticks":[0,1,2],
    "axisLabel":"the level $c$ (real values shown)",
    "markers":[{"v":0,"style":"ring","tone":"mute","at":0.5},{"v":0.5,"style":"ring","tone":"mute","at":0.6,"derived":"1/2"},
               {"v":1,"label":"rational $c$","note":"excluded","style":"ring","tone":"mute","at":0.7},
               {"v":1.5,"style":"ring","tone":"mute","at":0.8,"derived":"3/2"},{"v":2,"style":"ring","tone":"mute","at":0.9},
               {"v":1.414214,"label":"$c = \\sqrt{2}$","note":"covered","tone":"claim","at":2.2,"side":"below","derived":"sqrt 2"}]},
   {"primitive":"equation","from":4.2,"lines":[
     {"tex":r"D_c(\mathrm{Bun}_G) \;\simeq\; D_{-1/(rc)}(\mathrm{Bun}_{G^\vee})","tone":"accent","at":0.3,"size":48},
     {"tex":r"r = \text{lacing number of } G","tone":"soft","at":1.1,"size":30}]}],
  "beats":B((0.2,"Quantum Langlands deforms geometric Langlands by a level $c$"),
            (2.4,"The claim covers every irrational $c$, real or not; rational levels are left out"),
            (4.6,"Twisted D-modules at level $c$ match those for the dual group at $-1/(rc)$"))},
 {"form":"status","label":"Quantum geometric Langlands (Gaitsgory), irrational level",
  "statement":[r"D_c(\mathrm{Bun}_G) \simeq D_{-1/(rc)}(\mathrm{Bun}_{G^\vee}),\quad c \notin \mathbb{Q}"],
  "context":"Before: the classical, critical-level case by Gaitsgory–Raskin et al. (2024)",
  "stamp":"proved","note":"Rational and critical levels are excluded"},
 "none","No Lean; 119 pages, a single paper",NOREAD,
 [S("review 069, known_before","The classical (critical level) unramified geometric Langlands was proved by Gaitsgory–Raskin et al. (2024, 5-paper series)"),
  S("article, Quantum geometric Langlands at irrational level (family 069)","in 119 pages. Rational and critical levels are excluded.")])
print("done")
