import { cn } from "@/lib/utils"

// The four rewriters, run on the machine that builds this site: Intel Xeon @
// 2.80GHz, 4 cores, 15 GB of RAM under a 13.36 GiB memory cgroup, no GPU.
//
// GENERATED by gen_component.py from the run's analysis.json, which is published
// as /articles/qwen-image-2-1-pocket-rewriter/data/rewrites.json. Do not edit
// the numbers by hand; re-run the generator.
//
// Each arm rewrote the same seven gallery prompts once, seed 42, with the
// students' sampling (temperature 1.0, top-p 0.95, top-k 20) and, for the 9B,
// Qwen's own t2i profile on top: the shipped system prompt, thinking on,
// presence penalty 1.5. llama.cpp is ggml-org/llama.cpp at e6ab7c1, built with
// GGML_NATIVE on this CPU, 4 threads. Times are llama.cpp's own perf counters
// (prompt eval, eval) and wall-clock per rewrite; medians over the prompts, with
// one transformers run excluded from the timing because it overlapped other CPU
// work on this box (its text is kept). Peak RSS is VmHWM sampled every 0.5 s.
//
// Server-rendered, zero JS. Arithmetic is + - * / and toFixed only.

type Arm = {
  key: string
  label: string
  runtime: string
  n: number
  nClean: number
  wall: number
  prefill: number | null
  promptTokens: number
  gen: number
  thinking: number
  decodeTokS: number
  rss: number
  words: number
  dit: number
}

const ARMS: Arm[] = [
  {
    "key": "p08-q8",
    "label": "Pocket-0.8B",
    "runtime": "llama.cpp \u00b7 Q8_0 (theirs) \u00b7 0.81 GB",
    "n": 7,
    "nClean": 7,
    "wall": 14.09,
    "prefill": 0.21,
    "promptTokens": 45,
    "gen": 436,
    "thinking": 0,
    "decodeTokS": 35.03,
    "rss": 1783.8,
    "words": 342,
    "dit": 432
  },
  {
    "key": "p08-hf",
    "label": "Pocket-0.8B",
    "runtime": "transformers \u00b7 fp32 \u00b7 1.50 GB bf16 on disk",
    "n": 7,
    "nClean": 6,
    "wall": 54.98,
    "prefill": null,
    "promptTokens": 45,
    "gen": 446,
    "thinking": 0,
    "decodeTokS": 7.57,
    "rss": 4885.3,
    "words": 342,
    "dit": 441
  },
  {
    "key": "p2b-q8",
    "label": "Pocket-2B",
    "runtime": "llama.cpp \u00b7 Q8_0 (my conversion) \u00b7 2.00 GB",
    "n": 7,
    "nClean": 7,
    "wall": 26.79,
    "prefill": 0.47,
    "promptTokens": 45,
    "gen": 410,
    "thinking": 0,
    "decodeTokS": 17.15,
    "rss": 4203.6,
    "words": 316,
    "dit": 406
  },
  {
    "key": "t9b-q4km",
    "label": "PE-T2I (9B)",
    "runtime": "llama.cpp \u00b7 Q4_K_M (community) \u00b7 5.63 GB",
    "n": 7,
    "nClean": 7,
    "wall": 386.87,
    "prefill": 65.94,
    "promptTokens": 2473,
    "gen": 934,
    "thinking": 623,
    "decodeTokS": 3.02,
    "rss": 10377.7,
    "words": 348,
    "dit": 424
  }
]

const RAW_DIT = 41
const MAX_WALL = Math.max(...ARMS.map((a) => a.wall))
const FASTEST = Math.min(...ARMS.map((a) => a.wall))
const int = (n: number) => Math.round(n).toLocaleString("en-US")
const secs = (s: number) => (s >= 100 ? `${int(s)} s` : `${s.toFixed(1)} s`)

export function CpuRewriters() {
  const teacher = ARMS.find((a) => a.key.startsWith("t9b"))
  return (
    <figure
      className="my-8 overflow-hidden rounded-md border"
      data-cpu-rewriters={ARMS.length}
      aria-label="Measured wall-clock, tokens and memory of the Qwen-Image-2.1 prompt rewriters on four CPU cores"
    >
      <div className="border-b px-4 py-2 font-mono text-xs text-muted-foreground">
        seven gallery prompts, one rewrite each, four CPU cores — medians,
        measured
      </div>

      <div className="space-y-4 px-4 py-4">
        {ARMS.map((a) => (
          <div key={a.key} className="space-y-1.5">
            <div className="flex flex-wrap items-baseline justify-between gap-x-3">
              <p className="my-0 font-mono text-sm font-medium">
                {a.label}{" "}
                <span className="font-normal text-muted-foreground">
                  · {a.runtime}
                </span>
              </p>
            </div>
            <div className="grid grid-cols-[1fr_5rem] items-center gap-x-3 font-mono text-xs sm:grid-cols-[1fr_6rem]">
              <div className="relative h-4 rounded-sm bg-muted/50">
                <div
                  className={cn(
                    "absolute inset-y-0 left-0 rounded-sm",
                    a.key.startsWith("t9b") ? "bg-foreground/80" : "bg-foreground/45"
                  )}
                  style={{ width: `${Math.max((a.wall * 100) / MAX_WALL, 0.6)}%` }}
                />
              </div>
              <span className="text-right tabular-nums">{secs(a.wall)}</span>
            </div>
            <p className="my-0 font-mono text-xs text-muted-foreground">
              in{" "}
              <span className="text-foreground tabular-nums">{int(a.promptTokens)}</span>{" "}
              tok · out{" "}
              <span className="text-foreground tabular-nums">{int(a.gen)}</span>
              {a.thinking > 0 ? (
                <>
                  {" "}
                  (<span className="text-foreground tabular-nums">{int(a.thinking)}</span>{" "}
                  thinking)
                </>
              ) : null}{" "}
              · decode{" "}
              <span className="text-foreground tabular-nums">{a.decodeTokS.toFixed(1)}</span>{" "}
              tok/s{a.prefill !== null ? (
                <>
                  {" "}
                  · prefill{" "}
                  <span className="text-foreground tabular-nums">{secs(a.prefill)}</span>
                </>
              ) : null}{" "}
              · peak RSS{" "}
              <span className="text-foreground tabular-nums">
                {(a.rss / 1024).toFixed(2)} GiB
              </span>
            </p>
            <p className="my-0 font-mono text-xs text-muted-foreground">
              rewrite{" "}
              <span className="text-foreground tabular-nums">{int(a.words)}</span>{" "}
              words ·{" "}
              <span className="text-foreground tabular-nums">{int(a.dit)}</span>{" "}
              text tokens into the denoiser, against{" "}
              <span className="text-foreground tabular-nums">{int(RAW_DIT)}</span>{" "}
              for the raw prompt
            </p>
          </div>
        ))}
      </div>

      {teacher ? (
        <p className="my-0 border-t px-4 py-3 text-xs text-muted-foreground">
          The 9B takes{" "}
          <span className="font-mono text-foreground tabular-nums">
            {(teacher.wall / FASTEST).toFixed(0)}x
          </span>{" "}
          as long per rewrite as the 0.8B through llama.cpp, most of it decoding
          its own reasoning before it writes a word of the answer. It does fit:
          this box ran it in{" "}
          <span className="font-mono text-foreground tabular-nums">
            {(teacher.rss / 1024).toFixed(1)} GiB
          </span>
          . What the distillation buys on a CPU is time, not memory headroom.
        </p>
      ) : null}
    </figure>
  )
}
